[global]
developmentMode = false

[theme]
primaryColor = "#C76B1B"
backgroundColor = "#EEF2F6"
secondaryBackgroundColor = "#F8FAFC"
textColor = "#18212B"
font = "sans serif"

[server]
headless = true
